import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import ThemeProvider from '@/contexts/theme';
import { DEFAULT_THEME } from '@/constants/common';

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
	weight: ['200', '300', '400', '500', '500', '700', '800', '900'],
	display: 'swap',
	style: ['italic', 'normal']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
		>
			<body className={`${inter.variable} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme={DEFAULT_THEME}
					enableSystem={false}
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
